#!/bin/bash
# S.Chekanov. Process resolution plots and make histograms
# Example:
# from .x Resolution.C(1000,"output/DualTestBeam_1gev_e-_1000evt.root",1,"histos/hito_e-_1gev.root");

source ./particles.sh

  n=1
  MPart=${particle[$n]}
  echo "Run for particle ${MPart}"

  cmd="Resolution.C(1000,\"output/DualTestBeam_1gev_${MPart}.root\",1,\"histos/hist_${MPart}_1gev.root\")"
  root -q $cmd


#root -q 'Resolution.C(300,"output/DualTestBeam_0.5gev_mu-_100evt.root",0.5,"histos/hito_mu-_0.5gev.root")'


# root -b -l -q  Resolution.C \(1000,"output/DualTestBeam_1gev_e-_1000evt.root",1, "histos/hito_e-_1gev.root" \);

